# Default backend (perplexity, lmstudio, huggingface, or mistral)
backend: perplexity

# Output directory for documentation
output_directory: docs
base_directory: /path/to/your/project # Can also be set by means of the --input flag. If neither are provided, this defaults to the working directory.

# Directories to exclude from documentation generation
excluded_dirs:
  - venv
  - .venv
  - env
  - .env
  - node_modules
  - .git
  - __pycache__
  - .pytest_cache
  - .idea
  - .vscode
  # Add any other directories you want to exclude

# Perplexity
perplexity:
  api_key: your_api_key_here
  model: your_model_name

# LM Studio
lmstudio:
  port: 1234
  model: your_model_name
  streaming: true
  printstream: true

# HuggingFace
huggingface:
  api_key: your_api_key_here
  model: your_model_name
  temperature: 0.7
  max_new_tokens: 8192

# Mistral AI
mistral:
  api_key: your_api_key_here
  model: your_model_name
  temperature: 0.7
  max_tokens: 8192
