name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get version
        id: version
        run: echo "version=$(date +%d.%m.%y-%H:%M:%S)" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: bump
        if: github.ref == 'refs/heads/main'
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.bump.outputs.new_tag }} - ${{ steps.version.outputs.version }}
          tag: ${{ steps.bump.outputs.new_tag }}
          makeLatest: true